#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiBackEnd
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaAguas")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertConsumo(Consumo instance);
    partial void UpdateConsumo(Consumo instance);
    partial void DeleteConsumo(Consumo instance);
    partial void InsertContadore(Contadore instance);
    partial void UpdateContadore(Contadore instance);
    partial void DeleteContadore(Contadore instance);
    partial void InsertEstadoFatura(EstadoFatura instance);
    partial void UpdateEstadoFatura(EstadoFatura instance);
    partial void DeleteEstadoFatura(EstadoFatura instance);
    partial void InsertFatura(Fatura instance);
    partial void UpdateFatura(Fatura instance);
    partial void DeleteFatura(Fatura instance);
    #endregion
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Consumo> Consumos
		{
			get
			{
				return this.GetTable<Consumo>();
			}
		}
		
		public System.Data.Linq.Table<Contadore> Contadores
		{
			get
			{
				return this.GetTable<Contadore>();
			}
		}
		
		public System.Data.Linq.Table<EstadoFatura> EstadoFaturas
		{
			get
			{
				return this.GetTable<EstadoFatura>();
			}
		}
		
		public System.Data.Linq.Table<Fatura> Faturas
		{
			get
			{
				return this.GetTable<Fatura>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clientes")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCLiente;
		
		private string _Nome;
		
		private string _Apelido;
		
		private string _Morada;
		
		private string _Nif;
		
		private string _Contacto;
		
		private string _Email;
		
		private string _CodigoPostal;
		
		private string _Localidade;
		
		private bool _Ativo;
		
		private EntitySet<Contadore> _Contadores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCLienteChanging(int value);
    partial void OnIdCLienteChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnApelidoChanging(string value);
    partial void OnApelidoChanged();
    partial void OnMoradaChanging(string value);
    partial void OnMoradaChanged();
    partial void OnNifChanging(string value);
    partial void OnNifChanged();
    partial void OnContactoChanging(string value);
    partial void OnContactoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCodigoPostalChanging(string value);
    partial void OnCodigoPostalChanged();
    partial void OnLocalidadeChanging(string value);
    partial void OnLocalidadeChanged();
    partial void OnAtivoChanging(bool value);
    partial void OnAtivoChanged();
    #endregion
		
		public Cliente()
		{
			this._Contadores = new EntitySet<Contadore>(new Action<Contadore>(this.attach_Contadores), new Action<Contadore>(this.detach_Contadores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCLiente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCLiente
		{
			get
			{
				return this._IdCLiente;
			}
			set
			{
				if ((this._IdCLiente != value))
				{
					this.OnIdCLienteChanging(value);
					this.SendPropertyChanging();
					this._IdCLiente = value;
					this.SendPropertyChanged("IdCLiente");
					this.OnIdCLienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apelido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apelido
		{
			get
			{
				return this._Apelido;
			}
			set
			{
				if ((this._Apelido != value))
				{
					this.OnApelidoChanging(value);
					this.SendPropertyChanging();
					this._Apelido = value;
					this.SendPropertyChanged("Apelido");
					this.OnApelidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Morada", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Morada
		{
			get
			{
				return this._Morada;
			}
			set
			{
				if ((this._Morada != value))
				{
					this.OnMoradaChanging(value);
					this.SendPropertyChanging();
					this._Morada = value;
					this.SendPropertyChanged("Morada");
					this.OnMoradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nif", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string Nif
		{
			get
			{
				return this._Nif;
			}
			set
			{
				if ((this._Nif != value))
				{
					this.OnNifChanging(value);
					this.SendPropertyChanging();
					this._Nif = value;
					this.SendPropertyChanged("Nif");
					this.OnNifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="VarChar(9)")]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this.OnContactoChanging(value);
					this.SendPropertyChanging();
					this._Contacto = value;
					this.SendPropertyChanged("Contacto");
					this.OnContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPostal", DbType="VarChar(8)")]
		public string CodigoPostal
		{
			get
			{
				return this._CodigoPostal;
			}
			set
			{
				if ((this._CodigoPostal != value))
				{
					this.OnCodigoPostalChanging(value);
					this.SendPropertyChanging();
					this._CodigoPostal = value;
					this.SendPropertyChanged("CodigoPostal");
					this.OnCodigoPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localidade", DbType="VarChar(25)")]
		public string Localidade
		{
			get
			{
				return this._Localidade;
			}
			set
			{
				if ((this._Localidade != value))
				{
					this.OnLocalidadeChanging(value);
					this.SendPropertyChanging();
					this._Localidade = value;
					this.SendPropertyChanged("Localidade");
					this.OnLocalidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this.OnAtivoChanging(value);
					this.SendPropertyChanging();
					this._Ativo = value;
					this.SendPropertyChanged("Ativo");
					this.OnAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Contadore", Storage="_Contadores", ThisKey="IdCLiente", OtherKey="IdCliente")]
		public EntitySet<Contadore> Contadores
		{
			get
			{
				return this._Contadores;
			}
			set
			{
				this._Contadores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contadores(Contadore entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Contadores(Contadore entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Consumos")]
	public partial class Consumo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdConsumo;
		
		private int _IdContador;
		
		private System.DateTime _Data;
		
		private decimal _LeituraAtual;
		
		private decimal _ConsumoCalculado;
		
		private System.Nullable<int> _IdFatura;
		
		private EntityRef<Contadore> _Contadore;
		
		private EntityRef<Fatura> _Fatura;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdConsumoChanging(int value);
    partial void OnIdConsumoChanged();
    partial void OnIdContadorChanging(int value);
    partial void OnIdContadorChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnLeituraAtualChanging(decimal value);
    partial void OnLeituraAtualChanged();
    partial void OnConsumoCalculadoChanging(decimal value);
    partial void OnConsumoCalculadoChanged();
    partial void OnIdFaturaChanging(System.Nullable<int> value);
    partial void OnIdFaturaChanged();
    #endregion
		
		public Consumo()
		{
			this._Contadore = default(EntityRef<Contadore>);
			this._Fatura = default(EntityRef<Fatura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdConsumo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdConsumo
		{
			get
			{
				return this._IdConsumo;
			}
			set
			{
				if ((this._IdConsumo != value))
				{
					this.OnIdConsumoChanging(value);
					this.SendPropertyChanging();
					this._IdConsumo = value;
					this.SendPropertyChanged("IdConsumo");
					this.OnIdConsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContador", DbType="Int NOT NULL")]
		public int IdContador
		{
			get
			{
				return this._IdContador;
			}
			set
			{
				if ((this._IdContador != value))
				{
					if (this._Contadore.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdContadorChanging(value);
					this.SendPropertyChanging();
					this._IdContador = value;
					this.SendPropertyChanged("IdContador");
					this.OnIdContadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeituraAtual", DbType="Decimal(10,3) NOT NULL")]
		public decimal LeituraAtual
		{
			get
			{
				return this._LeituraAtual;
			}
			set
			{
				if ((this._LeituraAtual != value))
				{
					this.OnLeituraAtualChanging(value);
					this.SendPropertyChanging();
					this._LeituraAtual = value;
					this.SendPropertyChanged("LeituraAtual");
					this.OnLeituraAtualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumoCalculado", DbType="Decimal(10,3) NOT NULL")]
		public decimal ConsumoCalculado
		{
			get
			{
				return this._ConsumoCalculado;
			}
			set
			{
				if ((this._ConsumoCalculado != value))
				{
					this.OnConsumoCalculadoChanging(value);
					this.SendPropertyChanging();
					this._ConsumoCalculado = value;
					this.SendPropertyChanged("ConsumoCalculado");
					this.OnConsumoCalculadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFatura", DbType="Int")]
		public System.Nullable<int> IdFatura
		{
			get
			{
				return this._IdFatura;
			}
			set
			{
				if ((this._IdFatura != value))
				{
					if (this._Fatura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdFaturaChanging(value);
					this.SendPropertyChanging();
					this._IdFatura = value;
					this.SendPropertyChanged("IdFatura");
					this.OnIdFaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contadore_Consumo", Storage="_Contadore", ThisKey="IdContador", OtherKey="IdContador", IsForeignKey=true)]
		public Contadore Contadore
		{
			get
			{
				return this._Contadore.Entity;
			}
			set
			{
				Contadore previousValue = this._Contadore.Entity;
				if (((previousValue != value) 
							|| (this._Contadore.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Contadore.Entity = null;
						previousValue.Consumos.Remove(this);
					}
					this._Contadore.Entity = value;
					if ((value != null))
					{
						value.Consumos.Add(this);
						this._IdContador = value.IdContador;
					}
					else
					{
						this._IdContador = default(int);
					}
					this.SendPropertyChanged("Contadore");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fatura_Consumo", Storage="_Fatura", ThisKey="IdFatura", OtherKey="IdFatura", IsForeignKey=true)]
		public Fatura Fatura
		{
			get
			{
				return this._Fatura.Entity;
			}
			set
			{
				Fatura previousValue = this._Fatura.Entity;
				if (((previousValue != value) 
							|| (this._Fatura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fatura.Entity = null;
						previousValue.Consumos.Remove(this);
					}
					this._Fatura.Entity = value;
					if ((value != null))
					{
						value.Consumos.Add(this);
						this._IdFatura = value.IdFatura;
					}
					else
					{
						this._IdFatura = default(Nullable<int>);
					}
					this.SendPropertyChanged("Fatura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contadores")]
	public partial class Contadore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdContador;
		
		private int _IdCliente;
		
		private string _NumeroContador;
		
		private System.DateTime _DataInstalacao;
		
		private bool _Ativo;
		
		private EntitySet<Consumo> _Consumos;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdContadorChanging(int value);
    partial void OnIdContadorChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnNumeroContadorChanging(string value);
    partial void OnNumeroContadorChanged();
    partial void OnDataInstalacaoChanging(System.DateTime value);
    partial void OnDataInstalacaoChanged();
    partial void OnAtivoChanging(bool value);
    partial void OnAtivoChanged();
    #endregion
		
		public Contadore()
		{
			this._Consumos = new EntitySet<Consumo>(new Action<Consumo>(this.attach_Consumos), new Action<Consumo>(this.detach_Consumos));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdContador
		{
			get
			{
				return this._IdContador;
			}
			set
			{
				if ((this._IdContador != value))
				{
					this.OnIdContadorChanging(value);
					this.SendPropertyChanging();
					this._IdContador = value;
					this.SendPropertyChanged("IdContador");
					this.OnIdContadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroContador", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NumeroContador
		{
			get
			{
				return this._NumeroContador;
			}
			set
			{
				if ((this._NumeroContador != value))
				{
					this.OnNumeroContadorChanging(value);
					this.SendPropertyChanging();
					this._NumeroContador = value;
					this.SendPropertyChanged("NumeroContador");
					this.OnNumeroContadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInstalacao", DbType="Date NOT NULL")]
		public System.DateTime DataInstalacao
		{
			get
			{
				return this._DataInstalacao;
			}
			set
			{
				if ((this._DataInstalacao != value))
				{
					this.OnDataInstalacaoChanging(value);
					this.SendPropertyChanging();
					this._DataInstalacao = value;
					this.SendPropertyChanged("DataInstalacao");
					this.OnDataInstalacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this.OnAtivoChanging(value);
					this.SendPropertyChanging();
					this._Ativo = value;
					this.SendPropertyChanged("Ativo");
					this.OnAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contadore_Consumo", Storage="_Consumos", ThisKey="IdContador", OtherKey="IdContador")]
		public EntitySet<Consumo> Consumos
		{
			get
			{
				return this._Consumos;
			}
			set
			{
				this._Consumos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Contadore", Storage="_Cliente", ThisKey="IdCliente", OtherKey="IdCLiente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Contadores.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Contadores.Add(this);
						this._IdCliente = value.IdCLiente;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Consumos(Consumo entity)
		{
			this.SendPropertyChanging();
			entity.Contadore = this;
		}
		
		private void detach_Consumos(Consumo entity)
		{
			this.SendPropertyChanging();
			entity.Contadore = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EstadoFatura")]
	public partial class EstadoFatura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEstadoFatura;
		
		private string _Descricao;
		
		private EntitySet<Fatura> _Faturas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEstadoFaturaChanging(int value);
    partial void OnIdEstadoFaturaChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public EstadoFatura()
		{
			this._Faturas = new EntitySet<Fatura>(new Action<Fatura>(this.attach_Faturas), new Action<Fatura>(this.detach_Faturas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstadoFatura", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdEstadoFatura
		{
			get
			{
				return this._IdEstadoFatura;
			}
			set
			{
				if ((this._IdEstadoFatura != value))
				{
					this.OnIdEstadoFaturaChanging(value);
					this.SendPropertyChanging();
					this._IdEstadoFatura = value;
					this.SendPropertyChanged("IdEstadoFatura");
					this.OnIdEstadoFaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoFatura_Fatura", Storage="_Faturas", ThisKey="IdEstadoFatura", OtherKey="IdEstadoFatura")]
		public EntitySet<Fatura> Faturas
		{
			get
			{
				return this._Faturas;
			}
			set
			{
				this._Faturas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Faturas(Fatura entity)
		{
			this.SendPropertyChanging();
			entity.EstadoFatura = this;
		}
		
		private void detach_Faturas(Fatura entity)
		{
			this.SendPropertyChanging();
			entity.EstadoFatura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Faturas")]
	public partial class Fatura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFatura;
		
		private int _IdCliente;
		
		private int _IdContador;
		
		private System.DateTime _DataFatura;
		
		private decimal _Consumo;
		
		private decimal _ValorTotal;
		
		private int _IdEstadoFatura;
		
		private EntitySet<Consumo> _Consumos;
		
		private EntityRef<EstadoFatura> _EstadoFatura;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFaturaChanging(int value);
    partial void OnIdFaturaChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnIdContadorChanging(int value);
    partial void OnIdContadorChanged();
    partial void OnDataFaturaChanging(System.DateTime value);
    partial void OnDataFaturaChanged();
    partial void OnConsumoChanging(decimal value);
    partial void OnConsumoChanged();
    partial void OnValorTotalChanging(decimal value);
    partial void OnValorTotalChanged();
    partial void OnIdEstadoFaturaChanging(int value);
    partial void OnIdEstadoFaturaChanged();
    #endregion
		
		public Fatura()
		{
			this._Consumos = new EntitySet<Consumo>(new Action<Consumo>(this.attach_Consumos), new Action<Consumo>(this.detach_Consumos));
			this._EstadoFatura = default(EntityRef<EstadoFatura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFatura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdFatura
		{
			get
			{
				return this._IdFatura;
			}
			set
			{
				if ((this._IdFatura != value))
				{
					this.OnIdFaturaChanging(value);
					this.SendPropertyChanging();
					this._IdFatura = value;
					this.SendPropertyChanged("IdFatura");
					this.OnIdFaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContador", DbType="Int NOT NULL")]
		public int IdContador
		{
			get
			{
				return this._IdContador;
			}
			set
			{
				if ((this._IdContador != value))
				{
					this.OnIdContadorChanging(value);
					this.SendPropertyChanging();
					this._IdContador = value;
					this.SendPropertyChanged("IdContador");
					this.OnIdContadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataFatura", DbType="Date NOT NULL")]
		public System.DateTime DataFatura
		{
			get
			{
				return this._DataFatura;
			}
			set
			{
				if ((this._DataFatura != value))
				{
					this.OnDataFaturaChanging(value);
					this.SendPropertyChanging();
					this._DataFatura = value;
					this.SendPropertyChanged("DataFatura");
					this.OnDataFaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Consumo", DbType="Decimal(10,3) NOT NULL")]
		public decimal Consumo
		{
			get
			{
				return this._Consumo;
			}
			set
			{
				if ((this._Consumo != value))
				{
					this.OnConsumoChanging(value);
					this.SendPropertyChanging();
					this._Consumo = value;
					this.SendPropertyChanged("Consumo");
					this.OnConsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotal", DbType="Decimal(10,2) NOT NULL")]
		public decimal ValorTotal
		{
			get
			{
				return this._ValorTotal;
			}
			set
			{
				if ((this._ValorTotal != value))
				{
					this.OnValorTotalChanging(value);
					this.SendPropertyChanging();
					this._ValorTotal = value;
					this.SendPropertyChanged("ValorTotal");
					this.OnValorTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstadoFatura", DbType="Int NOT NULL")]
		public int IdEstadoFatura
		{
			get
			{
				return this._IdEstadoFatura;
			}
			set
			{
				if ((this._IdEstadoFatura != value))
				{
					if (this._EstadoFatura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEstadoFaturaChanging(value);
					this.SendPropertyChanging();
					this._IdEstadoFatura = value;
					this.SendPropertyChanged("IdEstadoFatura");
					this.OnIdEstadoFaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fatura_Consumo", Storage="_Consumos", ThisKey="IdFatura", OtherKey="IdFatura")]
		public EntitySet<Consumo> Consumos
		{
			get
			{
				return this._Consumos;
			}
			set
			{
				this._Consumos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoFatura_Fatura", Storage="_EstadoFatura", ThisKey="IdEstadoFatura", OtherKey="IdEstadoFatura", IsForeignKey=true)]
		public EstadoFatura EstadoFatura
		{
			get
			{
				return this._EstadoFatura.Entity;
			}
			set
			{
				EstadoFatura previousValue = this._EstadoFatura.Entity;
				if (((previousValue != value) 
							|| (this._EstadoFatura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EstadoFatura.Entity = null;
						previousValue.Faturas.Remove(this);
					}
					this._EstadoFatura.Entity = value;
					if ((value != null))
					{
						value.Faturas.Add(this);
						this._IdEstadoFatura = value.IdEstadoFatura;
					}
					else
					{
						this._IdEstadoFatura = default(int);
					}
					this.SendPropertyChanged("EstadoFatura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Consumos(Consumo entity)
		{
			this.SendPropertyChanging();
			entity.Fatura = this;
		}
		
		private void detach_Consumos(Consumo entity)
		{
			this.SendPropertyChanging();
			entity.Fatura = null;
		}
	}
}
#pragma warning restore 1591
